### ISSUE TITLE
Support extended behaviour for patterns

### ISSUE THREAD

**Issue by pombredanne** [darvid/python-hyperscan#11]
It would be useful to support extended pattern arguments.
Today, NULL is passed when adding patterns https://github.com/darvid/python-hyperscan/blob/efbc82ef213bbf0c19d522b691e74e04d90635cf/hyperscan/hyperscanmodule.c#L184 and compile does not accept extended pattern arguments.

**Comment by darvid** [comment]
added in v0.2.0

[usage examples](https://python-hyperscan.readthedocs.io/en/latest/usage/#extended-parameters) (also see the unit tests for more examples)
