### ISSUE TITLE
Update Request: Hyperscan 5.2.0 and the Literal API

### ISSUE THREAD

**Issue by JustinTimperio** [darvid/python-hyperscan#16]
Thanks for this library. I was wondering if you had time to update this to include the new Literal API added in [5.2.0](https://github.com/intel/hyperscan/tree/v5.2.0)?

**Comment by darvid** [comment]
I'll try to take a look at this by the end of this coming week, unless someone beats me to it.

**Comment by JustinTimperio** [comment]
Thanks!

**Comment by darvid** [comment]
sorry for the delay, working out some issues with CI and the Docker image used to build the manylinux compatible wheels. If you're interested in building from source, the [v0.1.4](https://github.com/darvid/python-hyperscan/tree/v0.1.4) branch works (pass `literal=True` to `Database.compile`.

**Comment by darvid** [comment]
0.1.4 is released, let me know if you have any issues

**Comment by JustinTimperio** [comment]
Thanks for updating this! 

Agreed on 2.7 support.
