### ISSUE TITLE
Possible reference leak during compilation?

### ISSUE THREAD

**Issue by msjyoo-work** [darvid/python-hyperscan#18]
Hi,

First of all, thanks for the library.

I noticed that not all items indexed by `PySequence_ITEM` is `Py_XDECREF'd`. Only the last  item indexed seems to be reference counted. Could this be a possible problem?

https://github.com/darvid/python-hyperscan/blob/master/hyperscan/hyperscanmodule.c#L181

**Comment by darvid** [comment]
definitely a problem, thanks for reporting!

**Comment by darvid** [comment]
fixed in 0.1.5
