### ISSUE TITLE
Support for serialising/deserialising database

### ISSUE THREAD

**Issue by halfdan** [darvid/python-hyperscan#20]
Hyperscan allows serialising a database. It would be great if this library had support to serialise a database to disk and restore it at a later point. 

https://intel.github.io/hyperscan/dev-reference/api_files.html#c.hs_serialize_database

**Comment by darvid** [comment]
so it doesn't look like I've documented this, but there are [dumps and loads](https://github.com/darvid/python-hyperscan/blob/master/hyperscan/hyperscanmodule.c#L779) methods on the ``Database`` object.

**Comment by darvid** [comment]
[documented](https://python-hyperscan.readthedocs.io/en/latest/usage/#serialization) as of v0.1.5, and renamed the functions to ``loadb``/``dumpb`` since they work with bytes and not strings.
