### ISSUE TITLE
Support for logical combinations

### ISSUE THREAD

**Issue by evrian** [darvid/python-hyperscan#21]
Since hyperscan 5.0 there has been support for combinations of patterns as described [here](https://intel.github.io/hyperscan/dev-reference/compilation.html#logical-combinations) and [here](https://software.intel.com/en-us/articles/logical-combinations-of-regular-expressions-in-hyperscan). 
I was unable to find the flag HS_FLAG_COMBINATION. Was wondering if this functionality is currently supported. Thanks!

**Comment by darvid** [comment]
not currently supported, will make sure to get it in the next release

**Comment by darvid** [comment]
added in v0.2.0
