### ISSUE TITLE
Can not open stream

### ISSUE THREAD

**Issue by mortezaardini** [darvid/python-hyperscan#33]
Hi
Is there any similar function to hs_open_stream (which is in C based hyperscan library) in python?
In examples, stream mode worked by 'with' keyword. Since I do not want to close the stream after exiting 'with' statement, I can not use this way and need something like hs_open_stream.
Thank you for your support.

**Comment by darvid** [comment]
you could call `__enter__` and `__exit__` (or `close`) manually:

```python
stream = hyperscan.Database(...)
stream.__enter__()
...
stream.__exit__()
```

**Comment by mortezaardini** [comment]
It solved my problem. 
Thank you.
