### ISSUE TITLE
Handling scan termination from match callback could be cleaner

### ISSUE THREAD

**Issue by kaiw** [darvid/python-hyperscan#41]
When calling scan methods, the `match_event_handler` callback can return a truthy value to indicate that the scan should be stopped. In the current error handling in `HANDLE_HYPERSCAN_ERR`, this is treated as a regular error and raises a `hyperscan.error`. While an early termination does feel like something that should show up in a return value, arguably it shouldn't be a regular exception.

As a closely related issue, `HANDLE_HYPERSCAN_ERR` nicely formats an error string, but discards the error int, which makes it awkward to conditionally handle errors. For example, storing the error int on the exception would allow a workaround to the above issue like:
```python
try:
    hs_db.scan(sample, match_event_handler=on_match)
except hyperscan.error as err:
    if err.code != HS_SCAN_TERMINATED:
        raise
```

**Comment by darvid** [comment]
as of the latest release I've added error classes for all the Hyperscan (and Chimera) error codes. I need to update the docs to reflect this, but you can check out the unit tests for an example. you should now be able to catch ``hyperscan.ScanTerminated`` which might make handling scan termination easier.

**Comment by kaiw** [comment]
Thank you! This is extremely helpful, and fixes the issue at least as far as I'm concerned.
